# Generated by Django 4.1.5 on 2023-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('title', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('reg_user', models.CharField(blank=True, max_length=45, null=True)),
                ('reg_date', models.CharField(blank=True, max_length=45, null=True)),
                ('mod_date', models.CharField(blank=True, max_length=45, null=True)),
                ('used_money', models.CharField(blank=True, max_length=45, null=True)),
                ('memo', models.CharField(blank=True, max_length=45, null=True)),
                ('account_bookcol', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'account_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('usercode', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
